// Generated by CoffeeScript 1.7.1
(function() {
  var query;

  query = (function() {
    var slice;
    if (!String.prototype.contains) {
      String.prototype.contains = function() {
        return String.prototype.indexOf.apply(this, arguments);
      };
    }
    slice = Function.prototype.call.bind(Array.prototype.slice);
    return function(param) {
      var elements;
      elements = void 0;
      if (param.split(" ").length !== 1 || param.contains("[")) {
        elements = slice(document.querySelectorAll(param));
      } else {
        if (param.charAt(0) === "#") {
          elements = [document.getElementById(param.slice(1))];
        } else if (param.charAt(0) === ".") {
          elements = slice(document.getElementsByClassName(param.slice(1)));
        } else {
          elements = slice(document.getElementsByTagName(param));
        }
      }
      return elements;
    };
  })();

}).call(this);
